name: supervol
channels:
  - simpleitk
  - defaults
  - conda-forge
dependencies:
  - pip=22.3.1
  - python=3.7.0
  - simpleitk
  - jupyterlab

  - pip:
    - comm==0.1.4
    - cycler==0.11.0
    - fonttools==4.38.0
    - ipywidgets==8.1.2
    - itk==5.3.0
    - itk-core==5.3.0
    - itk-filtering==5.3.0
    - itk-io==5.3.0
    - itk-numerics==5.3.0
    - itk-registration==5.3.0
    - itk-segmentation==5.3.0
    - jupyterlab-widgets==3.0.10
    - k3d==2.16.1
    - kiwisolver==1.4.5
    - matplotlib==3.5.3
    - msgpack==1.0.5
    - numpy==1.21.6
    - pandas==1.1.5
    - pillow==9.5.0
    - pyparsing==3.1.1
    - tqdm==4.66.1
    - traittypes==0.2.1
    - widgetsnbextension==4.0.10
