name: supervol
channels:
  - simpleitk
  - defaults
  - conda-forge
dependencies:
  - pip=22.3.1
  - python=3.7.0
  - simpleitk

  - pip:
    - itk==5.3.0
    - k3d==2.16.1
    - matplotlib==3.5.3
    - numpy==1.21.6
    - pandas==1.1.5
    - pillow==9.5.0
    - tqdm==4.66.1
  
